### ISSUE TITLE
segmentation fault  dtree dtree.raw dtree.patched -d -p, Linux 

### ISSUE THREAD

**Issue by dualra1n** [Ralph0045/dtree_patcher#2]
Hi, how are you?, hey sir I have an issue on Linux when I try to use dtree_patcher, I am trying to dual-boot and I need that, please. 

on gdb on Linux, it shows = "Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c9c17b in memmem () from /lib/x86_64-linux-gnu/libc.so.6"

any idea that can help me, thank you sir

**Comment by edwin170** [comment]
@Ralph0045
